[project]
name = "test-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fake-useragent>=2.2.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "playwright>=1.57.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
    "ty>=0.0.14",
]

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 79